name: tf_cloned
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.11.0=pyhd3eb1b0_1
  - afterimage=1.21=h4dd67e6_1003
  - appnope=0.1.2=py37hf985489_0
  - argon2-cffi=20.1.0=py37h4b544eb_2
  - astor=0.8.1=py37_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - awkward=1.0.1=py37h54c7649_2
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py37hf967b71_1001
  - bzip2=1.0.8=hc929b4f_4
  - c-ares=1.17.1=h9ed2024_0
  - c-compiler=1.1.3=h35c211d_0
  - ca-certificates=2020.10.14=0
  - cairo=1.16.0=h4ec454a_1007
  - cctools=949.0.1=hd9211c8_19
  - cctools_osx-64=949.0.1=h2f0f38f_19
  - certifi=2020.6.20=py37_0
  - cffi=1.14.4=py37hc5b2277_1
  - cfitsio=3.470=h01dc385_7
  - chardet=4.0.0=py37hf985489_1
  - clang=11.0.0=h694c41f_2
  - clang-11=11.0.0=default_h9e6edd0_2
  - clang_osx-64=11.0.0=hb91bd55_8
  - clangxx=11.0.0=default_h9e6edd0_2
  - clangxx_osx-64=11.0.0=h7e1b574_8
  - colorama=0.4.4=pyh9f0ad1d_0
  - compiler-rt=11.0.0=h01488ec_2
  - compiler-rt_osx-64=11.0.0=hd3c4e95_2
  - compilers=1.1.3=h694c41f_0
  - cryptography=3.3.1=py37haf76d9e_1
  - cxx-compiler=1.1.3=h926bf3e_0
  - cycler=0.10.0=py_2
  - davix=0.7.6=h61356a0_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - fftw=3.3.8=nompi_h5db8ec8_1114
  - fontconfig=2.13.1=h07ff6b0_1003
  - fortran-compiler=1.1.3=h6818c3e_0
  - freetype=2.10.4=h3f75d11_0
  - fribidi=1.0.10=hbcb3906_0
  - ftgl=2.4.0=h508da5b_0
  - future=0.18.2=py37hf985489_3
  - gast=0.2.2=py37_0
  - gdk-pixbuf=2.42.2=h976c81d_2
  - gettext=0.19.8.1=h7937167_1005
  - gfortran_impl_osx-64=9.3.0=h8668ab3_15
  - gfortran_osx-64=9.3.0=h0d18d9c_12
  - giflib=5.2.1=hbcb3906_2
  - gl2ps=1.4.2=h4cff582_0
  - glew=2.1.0=h046ec9c_2
  - glib=2.66.4=h22858aa_1
  - gmp=6.2.1=h2e338ed_0
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=h2e338ed_1001
  - graphviz=2.42.3=h98dfb87_0
  - grpcio=1.31.0=py37h7580e61_0
  - gsl=2.6=h71c5fe9_1
  - h5py=2.10.0=py37h0601b69_1
  - harfbuzz=2.7.4=hf28d55f_0
  - hdf5=1.10.6=nompi_hc5d9132_1113
  - icu=68.1=h74dc148_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2019.4=233
  - ipykernel=5.4.2=py37he01cfaa_0
  - ipyparallel=6.3.0=py37hf985489_2
  - ipython_genutils=0.2.0=py_1
  - isl=0.22.1=hb1e8313_2
  - jedi=0.18.0=py37hf985489_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.17.0=py_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.0.0a3=py37_1000
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.0=py37hf985489_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - keras=2.3.1=py37_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_1
  - keras-tuner=1.0.1=py_0
  - kiwisolver=1.3.1=py37h8ec247f_0
  - krb5=1.17.2=h60d9502_0
  - lcms2=2.11=h11f7e16_1
  - ld64=530=hd2e7500_19
  - ld64_osx-64=530=hea264c1_19
  - ldid=2.1.2=h7660a38_2
  - libblas=3.9.0=1_h508aa58_netlib
  - libcblas=3.9.0=3_h16b37ef_netlib
  - libclang-cpp11=11.0.0=default_h9e6edd0_2
  - libcurl=7.71.1=h9bf37e3_8
  - libcxx=11.0.0=h4c3b8ed_1
  - libedit=3.1.20191231=h1de35cc_1
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=h6c81a4c_15
  - libgfortran-devel_osx-64=9.3.0=h6c81a4c_15
  - libgfortran5=9.3.0=h6c81a4c_15
  - libglib=2.66.4=h7424822_1
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=3_h16b37ef_netlib
  - libllvm10=10.0.1=h009f743_3
  - libllvm11=11.0.0=hf85e3d2_0
  - libnghttp2=1.41.0=h7580e61_2
  - libpng=1.6.37=h7cec526_2
  - libprotobuf=3.13.0.1=hab81aa3_0
  - librsvg=2.50.2=hd7f2164_2
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.9.0=h8a08a2b_5
  - libtiff=4.2.0=h355d032_0
  - libwebp-base=1.1.0=hbcb3906_3
  - libxml2=2.9.10=h802ca4f_3
  - llvm-openmp=11.0.0=h73239a0_1
  - llvm-tools=11.0.0=hf85e3d2_0
  - llvmlite=0.35.0=py37hd32b0aa_0
  - lz4=3.1.1=py37hd56feec_0
  - lz4-c=1.9.2=hb1e8313_3
  - markdown=3.3.3=py37hecd8cb5_0
  - markupsafe=1.1.1=py37h395d20d_2
  - matplotlib=3.3.3=py37hf985489_0
  - matplotlib-base=3.3.3=py37hdacc966_0
  - metakernel=0.27.5=pyhd3deb0d_0
  - mistune=0.8.4=py37h4b544eb_1002
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37h9ed2024_0
  - mkl_fft=1.2.0=py37hc64f4ea_0
  - mkl_random=1.1.1=py37h959d312_0
  - mpc=1.1.0=ha57cd0f_1009
  - mpfr=4.0.2=h72d8aaf_1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37hf985489_3
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - notebook=6.1.6=py37hf985489_0
  - numba=0.52.0=py37h010c265_0
  - numpy=1.19.2=py37h456fd55_0
  - numpy-base=1.19.2=py37hcfb5961_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1j=h9ed2024_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.8=pyhd3deb0d_0
  - pandas=1.1.5=py37hb2f4e1b_0
  - pandoc=2.11.3.2=h35c211d_0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=ha86e081_5
  - parso=0.8.1=pyhd8ed1ab_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py37h40a97b9_0
  - pip=20.3.3=py37hecd8cb5_0
  - pixman=0.40.0=hbcb3906_0
  - portalocker=1.7.0=py37hc8dfbb8_1
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.8=pyha770c72_0
  - protobuf=3.13.0.1=py37hb1e8313_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydot=1.4.1=py37_0
  - pygments=2.7.3=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37h4b544eb_1
  - pysocks=1.7.1=py37hf985489_3
  - pythia8=8.244=py37h54c7649_2
  - python=3.7.9=h26836e1_0
  - python-dateutil=2.8.1=py_0
  - python-xxhash=2.0.0=py37hf967b71_1
  - python_abi=3.7=1_cp37m
  - pytz=2020.5=pyhd3eb1b0_0
  - pyyaml=5.3.1=py37h395d20d_1
  - pyzmq=20.0.0=py37h47fd9b3_1
  - readline=8.0=h1de35cc_0
  - requests=2.25.1=pyhd3deb0d_0
  - root=6.22.6=py37ha0830e8_0
  - root-binaries=6.22.6=py37ha0830e8_0
  - root-dependencies=6.22.6=py37ha0830e8_0
  - root_base=6.22.6=py37h1ff80a4_0
  - root_numpy=4.8.0=py37h5a6a189_10
  - scikit-learn=0.23.2=py37h959d312_0
  - scipy=1.6.0=py37h6bb7d36_0
  - send2trash=1.5.0=py_0
  - setuptools=51.0.0=py37hecd8cb5_2
  - six=1.15.0=py37hecd8cb5_0
  - sqlite=3.34.0=h17101e1_0
  - tabulate=0.8.7=pyh9f0ad1d_0
  - tapi=1100.0.11=h9ce4665_0
  - tbb=2020.2=h926bf3e_2
  - tbb-devel=2020.2=h926bf3e_2
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=mkl_py37hda344b4_0
  - tensorflow-base=2.0.0=mkl_py37h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - terminado=0.9.1=py37hf985489_1
  - terminaltables=3.1.0=py_0
  - testpath=0.4.4=py_0
  - theano=1.0.4=py37h04f5b5a_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py37h4b544eb_0
  - tqdm=4.56.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - uproot=4.0.0=py37hf985489_1
  - uproot-base=4.0.0=pyh8a188c0_1
  - urllib3=1.26.3=pyhd8ed1ab_0
  - vdt=0.4.3=h046ec9c_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h1de35cc_1
  - xrootd=5.0.3=py37h33e3a25_0
  - xxhash=0.8.0=h35c211d_3
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.3=h74dc148_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstandard=0.14.1=py37h54c7649_0
  - zstd=1.4.8=h62961b2_0
  - pip:
    - ipython==7.19.0
prefix: /Users/ho-fung/opt/miniconda3/envs/tf_cloned
